import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTelemedicineSessions1784131706135 implements MigrationInterface {
    name = 'AddTelemedicineSessions1784131706135'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_payments_patient_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_tenant_invoice"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_tenant_patient"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_tenant_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_invoice_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_patients_tenant_email_portal"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_tenant_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_tenant_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscriptions_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscriptions_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscription_invoices_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscription_invoices_subscription_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscription_invoices_tenant_subscription"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscription_invoices_tenant_status"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('trial_ending', 'trial_expired', 'payment_failed', 'payment_succeeded', 'renewal_upcoming', 'subscription_cancelled', 'plan_changed', 'dunning_reminder', 'account_suspended', 'general')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "user_id" uuid, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'general', "title" character varying(255) NOT NULL, "message" text NOT NULL, "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'medium', "action_url" character varying(500), "action_label" character varying(100), "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, "email_sent" boolean NOT NULL DEFAULT false, "email_sent_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d93ddd7e1b890535ecafbb334e" ON "notifications" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_519d212c491ea2aff5ad82ac3d" ON "notifications" ("tenant_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d540732e0ccb1b9e7e5050133" ON "notifications" ("tenant_id", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_abf596c7a240669cf50d9d2b04" ON "notifications" ("tenant_id", "is_read") `);
        await queryRunner.query(`CREATE TABLE "portal_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "conversation_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "sender_type" character varying(20) NOT NULL, "sender_name" character varying(255) NOT NULL, "body" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, "attachments" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0a01c7f502d9f528893f979066b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fb3c417c6608570b4f1f528360" ON "portal_messages" ("conversation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c129d8daa763825dffe3fac03" ON "portal_messages" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "portal_conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "patient_id" uuid NOT NULL, "patient_name" character varying(255) NOT NULL, "provider_id" uuid, "provider_name" character varying(255), "subject" character varying(255) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'open', "priority" character varying(20) NOT NULL DEFAULT 'normal', "last_message_at" TIMESTAMP WITH TIME ZONE, "unread_by_patient" integer NOT NULL DEFAULT '0', "unread_by_provider" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_56d904b1f9cdf20e9dd47976c9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ce4cb1a274d8914cb03d44d6a4" ON "portal_conversations" ("tenant_id", "provider_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0e0124552d7f1426662ad03f5" ON "portal_conversations" ("tenant_id", "patient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7331da13ea7e3acdae2254667" ON "portal_conversations" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "telemedicine_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "appointment_id" uuid, "patient_id" uuid NOT NULL, "provider_id" uuid NOT NULL, "room_id" character varying(100) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'scheduled', "participants" jsonb NOT NULL DEFAULT '[]', "chat_messages" jsonb NOT NULL DEFAULT '[]', "shared_files" jsonb NOT NULL DEFAULT '[]', "started_at" TIMESTAMP WITH TIME ZONE, "ended_at" TIMESTAMP WITH TIME ZONE, "duration_minutes" integer, "recording_consent" boolean NOT NULL DEFAULT false, "recording_status" character varying(50) NOT NULL DEFAULT 'not_started', "recording_url" text, "transcript" text, "soap_note" jsonb NOT NULL DEFAULT '{}', "suggested_codes" jsonb, "encounter_id" uuid, "superbill_id" uuid, "provider_notes" text, "connection_quality" jsonb, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_8b936dfd35f334c5a332cea86b4" UNIQUE ("room_id"), CONSTRAINT "PK_6d75e15b799edce1fe22987721d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72e0982f1a31c6a567b56e2930" ON "telemedicine_sessions" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7cf287769a40cbdfcffe61bf16" ON "telemedicine_sessions" ("tenant_id", "room_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_662adfa39e605ca29b072801a5" ON "telemedicine_sessions" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2305a36f330da44f1c07103a24" ON "telemedicine_sessions" ("tenant_id", "provider_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c911c02f768dcfff7b9319ae25" ON "telemedicine_sessions" ("tenant_id", "patient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b94d668f91c06ba659b8df9d2" ON "telemedicine_sessions" ("tenant_id", "appointment_id") `);
        await queryRunner.query(`ALTER TABLE "patients" ALTER COLUMN "mfa_enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" ALTER COLUMN "portal_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."subscriptions_billingcycle_enum" RENAME TO "subscriptions_billingcycle_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_billing_cycle_enum" AS ENUM('monthly', 'annual')`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "billing_cycle" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "billing_cycle" TYPE "public"."subscriptions_billing_cycle_enum" USING "billing_cycle"::"text"::"public"."subscriptions_billing_cycle_enum"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "billing_cycle" SET DEFAULT 'monthly'`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_billingcycle_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_9109b53fca5cef7720aca72974" ON "payments" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d2ce22525e1801b449f24a989" ON "payments" ("patient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8476231fa87ebf08c399506a87" ON "payments" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ffc987be5e4aee0b25016d2ae9" ON "payments" ("tenant_id", "patient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_94c1cbbc0fa78325d5117bc7e1" ON "payments" ("tenant_id", "invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_109638590074998bb72a2f2cf0" ON "users" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd3c8b88ab3e4c27c8494a3ea7" ON "users" ("tenant_id", "role") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9f4c2efab52114c4e99e28efb" ON "users" ("tenant_id", "email") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6ac03431c311ccb8bbd7d3af1" ON "subscriptions" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a5257dfb60f446b19c287f416" ON "subscription_invoices" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f183991dc9bcbda39fa614193" ON "subscription_invoices" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_70ceeba6a982b46dc324207862" ON "subscription_invoices" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfc86cbad95ba5d735c3d147e4" ON "subscription_invoices" ("tenant_id", "subscription_id") `);
        await queryRunner.query(`ALTER TABLE "portal_messages" ADD CONSTRAINT "FK_fb3c417c6608570b4f1f5283605" FOREIGN KEY ("conversation_id") REFERENCES "portal_conversations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "portal_messages" DROP CONSTRAINT "FK_fb3c417c6608570b4f1f5283605"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfc86cbad95ba5d735c3d147e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70ceeba6a982b46dc324207862"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f183991dc9bcbda39fa614193"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a5257dfb60f446b19c287f416"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6ac03431c311ccb8bbd7d3af1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f4c2efab52114c4e99e28efb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd3c8b88ab3e4c27c8494a3ea7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_109638590074998bb72a2f2cf0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94c1cbbc0fa78325d5117bc7e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffc987be5e4aee0b25016d2ae9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8476231fa87ebf08c399506a87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d2ce22525e1801b449f24a989"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9109b53fca5cef7720aca72974"`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_billingcycle_enum_old" AS ENUM('monthly', 'annual')`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "billing_cycle" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "billing_cycle" TYPE "public"."subscriptions_billingcycle_enum_old" USING "billing_cycle"::"text"::"public"."subscriptions_billingcycle_enum_old"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ALTER COLUMN "billing_cycle" SET DEFAULT 'monthly'`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_billing_cycle_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."subscriptions_billingcycle_enum_old" RENAME TO "subscriptions_billingcycle_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" ALTER COLUMN "portal_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" ALTER COLUMN "mfa_enabled" DROP NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b94d668f91c06ba659b8df9d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c911c02f768dcfff7b9319ae25"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2305a36f330da44f1c07103a24"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_662adfa39e605ca29b072801a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cf287769a40cbdfcffe61bf16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72e0982f1a31c6a567b56e2930"`);
        await queryRunner.query(`DROP TABLE "telemedicine_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7331da13ea7e3acdae2254667"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0e0124552d7f1426662ad03f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce4cb1a274d8914cb03d44d6a4"`);
        await queryRunner.query(`DROP TABLE "portal_conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c129d8daa763825dffe3fac03"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb3c417c6608570b4f1f528360"`);
        await queryRunner.query(`DROP TABLE "portal_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abf596c7a240669cf50d9d2b04"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d540732e0ccb1b9e7e5050133"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_519d212c491ea2aff5ad82ac3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d93ddd7e1b890535ecafbb334e"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_subscription_invoices_tenant_status" ON "subscription_invoices" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_subscription_invoices_tenant_subscription" ON "subscription_invoices" ("tenant_id", "subscription_id") `);
        await queryRunner.query(`CREATE INDEX "idx_subscription_invoices_subscription_id" ON "subscription_invoices" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "idx_subscription_invoices_tenant_id" ON "subscription_invoices" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "idx_subscriptions_status" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_subscriptions_tenant_id" ON "subscriptions" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_tenant_role" ON "users" ("tenant_id", "role") `);
        await queryRunner.query(`CREATE INDEX "idx_users_tenant_id" ON "users" ("tenant_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_tenant_email" ON "users" ("tenant_id", "email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_patients_tenant_email_portal" ON "patients" ("tenant_id", "email") WHERE ((email IS NOT NULL) AND (portal_active = true))`);
        await queryRunner.query(`CREATE INDEX "idx_payments_invoice_id" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_tenant_id" ON "payments" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_tenant_status" ON "payments" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_tenant_patient" ON "payments" ("tenant_id", "patient_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_tenant_invoice" ON "payments" ("tenant_id", "invoice_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_patient_id" ON "payments" ("patient_id") `);
    }

}
