import { Injectable, Logger } from '@nestjs/common';
import {
  SubscriptionProvider,
  CreateSubscriptionRequest,
  CreateSubscriptionResponse,
  CancelSubscriptionRequest,
  CancelSubscriptionResponse,
  ChangePlanRequest,
  ChangePlanResponse,
  SubscriptionWebhookEvent,
  PaymentMethodDetails,
  GetPaymentMethodRequest,
  CreateSetupIntentRequest,
  CreateSetupIntentResponse,
  AttachPaymentMethodRequest,
  AttachPaymentMethodResponse,
  DetachPaymentMethodRequest,
  DetachPaymentMethodResponse,
  SetDefaultPaymentMethodRequest,
  SetDefaultPaymentMethodResponse,
  CreateCustomerPortalSessionRequest,
  CreateCustomerPortalSessionResponse,
  RetryInvoiceRequest,
  RetryInvoiceResponse,
} from './subscription-provider.interface';

/**
 * Mock subscription provider for development without Stripe.
 * Simulates a 14-day trial then active subscription.
 * Also simulates payment method management with in-memory storage.
 */
@Injectable()
export class MockSubscriptionProvider implements SubscriptionProvider {
  readonly name = 'mock';
  private readonly logger = new Logger(MockSubscriptionProvider.name);

  // In-memory payment method store: keyed by stripeCustomerId
  private paymentMethods: Map<string, PaymentMethodDetails[]> = new Map();

  async createSubscription(request: CreateSubscriptionRequest): Promise<CreateSubscriptionResponse> {
    const now = new Date();
    const trialEnd = new Date(now.getTime() + (request.trialDays ?? 14) * 24 * 60 * 60 * 1000);
    const periodEnd =
      request.billingCycle === 'annual'
        ? new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000)
        : new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

    this.logger.log(
      `Mock subscription created for tenant ${request.tenantName} (plan: ${request.planTier}, cycle: ${request.billingCycle})`,
    );

    // Seed a mock payment method for the customer
    const mockCustomerId = `mock_cus_${request.tenantId.substring(0, 8)}`;
    this.seedMockPaymentMethod(mockCustomerId);

    return {
      providerSubscriptionId: `mock_sub_${request.subscriptionId.substring(0, 8)}`,
      providerCustomerId: mockCustomerId,
      status: 'trialing',
      currentPeriodStart: now,
      currentPeriodEnd: periodEnd,
      trialEnd,
    };
  }

  async cancelSubscription(
    request: CancelSubscriptionRequest,
  ): Promise<CancelSubscriptionResponse> {
    this.logger.log(`Mock subscription ${request.providerSubscriptionId} cancelled`);
    return {
      status: 'canceled',
      cancelAtPeriodEnd: request.cancelAtPeriodEnd ?? false,
      canceledAt: request.cancelAtPeriodEnd ? null : new Date(),
    };
  }

  async changePlan(request: ChangePlanRequest): Promise<ChangePlanResponse> {
    this.logger.log(`Mock subscription ${request.providerSubscriptionId} plan changed`);
    return {
      providerSubscriptionId: request.providerSubscriptionId,
      status: 'active',
    };
  }

  parseWebhook(rawBody: string, _signature: string): SubscriptionWebhookEvent {
    const event = JSON.parse(rawBody) as Record<string, any>;
    const obj = event.data?.object ?? {};
    return {
      providerSubscriptionId: obj.id ?? '',
      status: obj.status ?? 'active',
      currentPeriodStart: obj.current_period_start
        ? new Date(obj.current_period_start * 1000)
        : undefined,
      currentPeriodEnd: obj.current_period_end
        ? new Date(obj.current_period_end * 1000)
        : undefined,
      trialEnd: obj.trial_end ? new Date(obj.trial_end * 1000) : null,
      rawEvent: event,
    };
  }

  // ── Payment Method Management (Phase 1, 3) ────────────────────────

  async getPaymentMethods(request: GetPaymentMethodRequest): Promise<PaymentMethodDetails[]> {
    const methods = this.paymentMethods.get(request.stripeCustomerId) ?? [];
    this.logger.log(`Mock getPaymentMethods for ${request.stripeCustomerId}: ${methods.length} methods`);
    return methods;
  }

  async createSetupIntent(request: CreateSetupIntentRequest): Promise<CreateSetupIntentResponse> {
    const setupIntentId = `mock_seti_${Date.now()}`;
    this.logger.log(`Mock SetupIntent created: ${setupIntentId}`);
    return {
      clientSecret: `${setupIntentId}_secret_mock`,
      setupIntentId,
    };
  }

  async attachPaymentMethod(
    request: AttachPaymentMethodRequest,
  ): Promise<AttachPaymentMethodResponse> {
    // In mock mode, the payment method ID is generated by the frontend
    // We create a mock PaymentMethodDetails from it
    const pmId = request.stripePaymentMethodId || `mock_pm_${Date.now()}`;
    const paymentMethod: PaymentMethodDetails = {
      stripePaymentMethodId: pmId,
      type: 'card',
      cardBrand: 'visa',
      cardLast4: '4242',
      cardExpMonth: 12,
      cardExpYear: 2027,
      cardFunding: 'credit',
      billingName: null,
      billingAddress: null,
      isDefault: request.setAsDefault ?? true,
      isHsaFsa: false,
      metadata: {},
    };

    const methods = this.paymentMethods.get(request.stripeCustomerId) ?? [];
    if (request.setAsDefault) {
      methods.forEach((m) => (m.isDefault = false));
    }
    methods.push(paymentMethod);
    this.paymentMethods.set(request.stripeCustomerId, methods);

    this.logger.log(`Mock payment method attached to ${request.stripeCustomerId}: ${pmId}`);
    return { success: true, paymentMethod };
  }

  async detachPaymentMethod(
    request: DetachPaymentMethodRequest,
  ): Promise<DetachPaymentMethodResponse> {
    // Remove from all customers
    for (const [customerId, methods] of this.paymentMethods.entries()) {
      const filtered = methods.filter((m) => m.stripePaymentMethodId !== request.stripePaymentMethodId);
      this.paymentMethods.set(customerId, filtered);
    }
    this.logger.log(`Mock payment method detached: ${request.stripePaymentMethodId}`);
    return { success: true };
  }

  async setDefaultPaymentMethod(
    request: SetDefaultPaymentMethodRequest,
  ): Promise<SetDefaultPaymentMethodResponse> {
    const methods = this.paymentMethods.get(request.stripeCustomerId) ?? [];
    methods.forEach((m) => {
      m.isDefault = m.stripePaymentMethodId === request.stripePaymentMethodId;
    });
    this.paymentMethods.set(request.stripeCustomerId, methods);
    this.logger.log(`Mock default payment method set: ${request.stripePaymentMethodId}`);
    return { success: true };
  }

  // ── Customer Portal (Phase 4) ─────────────────────────────────────

  async createCustomerPortalSession(
    request: CreateCustomerPortalSessionRequest,
  ): Promise<CreateCustomerPortalSessionResponse> {
    this.logger.log(`Mock customer portal session for ${request.stripeCustomerId}`);
    return { url: request.returnUrl };
  }

  // ── Retry Invoice / Dunning (Phase 2) ─────────────────────────────

  async retryInvoice(request: RetryInvoiceRequest): Promise<RetryInvoiceResponse> {
    this.logger.log(`Mock retry invoice ${request.stripeInvoiceId} with PM ${request.stripePaymentMethodId}`);
    return { success: true, status: 'paid' };
  }

  // ── Private helpers ───────────────────────────────────────────────

  private seedMockPaymentMethod(customerId: string): void {
    if (this.paymentMethods.has(customerId)) return;
    this.paymentMethods.set(customerId, [
      {
        stripePaymentMethodId: `mock_pm_${customerId.substring(8)}`,
        type: 'card',
        cardBrand: 'visa',
        cardLast4: '4242',
        cardExpMonth: 12,
        cardExpYear: 2027,
        cardFunding: 'credit',
        billingName: 'Test Practice',
        billingAddress: {
          line1: '100 Healthcare Blvd',
          city: 'Springfield',
          state: 'IL',
          postalCode: '62701',
          country: 'US',
        },
        isDefault: true,
        isHsaFsa: false,
        metadata: {},
      },
    ]);
  }
}
